apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: my-app
    type: frontend
spec:
  template:
    metadata:
      name: my-app
      labels:
        app: my-app
        type: frontend
  replicas: 3
  selector:
    matchLabels:
      app: my-app
